######################################################################
# 국내TV 파일처리 설정파일 (Basic)
# 버전 : 1.0
######################################################################


  ######################################################################
  # 이 값은  "다운로드 폴더처리"(기본처리)에서는 사용하지 않고, "설정파일을 사용하는 처리" 시에만 사용
  # 값을 모두 채우고 "설정파일을 사용하는 처리"에서 동작하면 기본처리와 동일.
  
- 소스 폴더 : 기본처리에는 DB 설정값 사용
  타겟 폴더 : 기본처리에는 DB 설정값 사용
  에러 폴더 : 기본처리에는 DB 설정값 사용
  타겟 폴더 구조 : 기본처리에는 DB 설정값 사용



  ######################################################################
  # 경로 설정
  # {error} : 에러 폴더 활용한 경로나 절대경로

  경로 설정:
    no_tv : "{error}/no_tv"       # tv 형식이 아닌 경우 (회차를 찾을 수 없을 때)
    no_meta : "{error}/no_meta"   # 메타 매칭이 실패할 경우 파일이 이동할 error 폴더내의 폴더명
    ftv : "{error}/ftv"           # 메타 매칭시 ftv로 인식될 때 이동할 폴더. 전제조건 : 파일명이 모두 영문
    test : "{error}/test"         # 이 외는 이동 폴더에 사용할 규칙
    #av : "/data/mnt/av/incoming"

    
  ######################################################################
  # 미사용 : 항상 폴더명 규칙에 의해 이동
  # 방송제목포함 : 타겟 폴더를 탐색하여 메타 제목을 포함하는 폴더가 있으면 이동
  # 완전일치 : 완전히 일치하는 폴더가 있으면 이동
  
  타겟 폴더 탐색 사용 : "미사용"


  ######################################################################
  # true : no_meta 폴더에 방송별 폴더를 만들고 파일을 이동
  # false : no_meta 폴더 루트에 파일 이동

  메타 검색 실패시 방송별 폴더 생성 : false


  ######################################################################
  # 파일처리를 하기 전 처리

  전처리:
    삭제: # 정규식 매칭시 삭제. 단어나 확장자.  re.search(규칙) 사용
      - "nfo$"
      - "exe$"
      - "txt$"
      - "\\[예고\\]"
      
    이동:  # 정규식 매칭시 이동. 이동폴더는 foldername에서 설정 혹은 절대경로
      #av:
      #  - '^\\w+-\\d+\\.[\w\d]{3}$'

      test:
         - "conf$"

      # /data/mnt/토렌트/111:
      #  - "210312"

      # /data/영화:
      #  - 2160p
      #  - REMUX

    변환: # re.sub(소스, 타겟, 파일명) 실행
      
      # 월화드라마, 특별기획드라마, 제거
      - source : "^\\w{2,}드라마"
        target : ""

      # 설,추석 특집
      - source : "^\\w+\\s?특집"
        target : ""

      # Deresisi 릴 
      - source : "^(?P<title>(.*?))\\s(?P<all>E\\d+.*?Deresisi.*?mp4)$"
        target : "\\g<title>.\\g<all>"

      - source : "\\.최종회\\."
        target : "."

      - source : "\\.최종\\."
        target : "."

      - source : "\\.첫회\\."
        target : "."
      
      - source : "\\.첫방송\\."
        target : "."

      - source : "\\s\\d{7,}"
        target : ""

      - source : "써치"
        target : "진실을 검색하다, 써치"



  ######################################################################
  # 에피소드 번호 삭제
  에피소드 번호 삭제 목록:
    - "사사건건"
    - "남북의 창"
    - "MBC뉴스데스크"
    - "SBS 8뉴스"
    - "다큐 인사이트"
    - "KBS 뉴스9"


  ######################################################################
  # 방송명 부분을 메타 탐색시 변경하여 검색
  # 전처리-변환 옵션은 파일명을 변경하지만 이 옵션은 파일명은 유지한채 검색시에만 사용
  # re.IGNORECASE 사용

  검색어 변경:
    # [] 안에 있는 문자 제거
    - source : "\\[.*?\\]"
      target : ""

    - source : "mine"
      target : "마인"

    

        
  ######################################################################
  # Daum에서 검색되지 않는 방송은 ott 전용 컨텐츠일 가능성이 높음
  # 장르로 이를 구분

  메타 사이트별 장르 접두사:
    daum: ""
    tving: 티빙
    wavve : 웨이브


  ######################################################################
  # 메타 사이트에서 검색되는 장르 변경 규칙
  # 매칭 사이트별 장르 접두사가 있는 경우 포함하여 수정
  # 규칙에 없는 경우 동일

  장르 변경 규칙: 
    # 교양 
    # 뉴스
    # 다큐멘터리
    # 드라마
    생활 : 교양
    # 스포츠
    # 시사
    # 애니메이션
    # 어린이
    연예정보 : 예능
    웹예능 : 예능
    # 예능
    # 음악
    # 특집프로그램
    미국드라마 : 해외
    중국드라마 : 해외
    영국드라마 : 해외
    일본드라마 : 해외
    대만드라마 : 해외
    기타국가드라마 : 해외

    웨이브 골프 : 스포츠
    웨이브 교양 : 교양
    웨이브 기타 : 웨이브
    웨이브 뉴스 : 뉴스
    웨이브 다큐 : 다큐멘터리
    웨이브 단편 : 웨이브
    웨이브 대드 : 해외
    웨이브 라이프 : 웨이브
    웨이브 리얼리티 : 해외
    웨이브 뮤직 : 음악
    웨이브 미드 : 해외
    웨이브 수사 : 해외
    웨이브 시대극 : 해외
    웨이브 시사 : 시사
    웨이브 어드벤처 : 해외
    웨이브 웹드라마 : 웨이브
    웨이브 음악 : 음악
    웨이브 일드 : 해외
    웨이브 중드 : 해외
    웨이브 캐리TV : 어린이
    웨이브 토크 : 웨이브
    웨이브 푸드 : 웨이브
    
    티빙 교양 : 교양
    # 해외 드라마도 드라마에 포함. 한국 드라마는 거의 Daum에서 찾아지기 때문에 티빙 드라마로 매칭되는 것은 거의 해외
    티빙 드라마 : 해외
    티빙 디지털오리지널 : 티빙
    티빙 스포츠 : 스포츠
    티빙 애니메이션 : 애니메이션
    티빙 예능 : 티빙
    티빙 키즈 : 어린이
    # 드라마가 아닌 장르
    티빙 해외시리즈 : 해외


  #PLEX_MATE_SCAN:
  #  - URL: "http://localhost:8888"
  #    경로변경:
  #      - 소스: "L:"
  #        타겟: "H:\\내 드라이브"
  #    #  - 소스:
  #    #    타켓: